# Netlify configuration file
[build]
  command = "node scripts/netlify-build.js"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Netlify Next.js plugin handles functions automatically
[[plugins]]
package = "@netlify/plugin-nextjs"
